# Generated by Django 3.0.5 on 2020-05-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
